name: Lint and run tests

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
    steps:
    - uses: actions/checkout@v3

    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Check if uv.lock is up-to-date
      run: uv lock --check

    - name: Install dependencies
      run: uv sync --extra linters

    - name: Run ruff format
      run: uv run ruff format .

    - name: Run ruff check
      run: uv run ruff check .

    - name: Run codespell
      run: uv run codespell .

    - name: Run interrogate
      run: uv run interrogate --verbose .

    - name: Run tests and coverage
      run: |
          uv run -m coverage run -m unittest
          uv run -m coverage report

